### ISSUE TITLE
Can't find bundle for base name render, locale x_x

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lodossDev/jmugen#5]
```
What steps will reproduce the problem?

1. java -jar JMugen.jar 

What is the expected output? What do you see instead?

Exception in thread "main" java.util.MissingResourceException: Can't find
bundle for base name render, locale nl_BE
    at
java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1278)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:733)
    at org.lee.mugen.renderer.GraphicsWrapper.init(GraphicsWrapper.java:10)
    at org.lee.mugen.test.TestMenu.main(TestMenu.java:11)
    at org.mugen.launch.Launch.main(Launch.java:13)



What version of the product are you using? On what operating system?

The OS I'm using is ubuntu.

Please provide any additional information below.

My question is what is your default locale when programming?

I tried en-US with the following command :

java -Duser.language=en -Duser.region=US -jar /Mugen/JMugen.beta/JMugen.jar

But this gives a similar output.

thanks,

Marlo
```

Original issue reported on code.google.com by `Marlo.St...@gmail.com` on 29 Jun 2009 at 9:14

**Comment by GoogleCodeExporter** [comment]
```
Mario, you are missing the jar "commons.collections". In gentoo I fixed this 
with:

emerge commons-collections

Install it with aptitude/yum or whatever else your distro uses for package 
management.
```

Original comment by `you.dont...@gmail.com` on 22 Jul 2009 at 5:10

**Comment by GoogleCodeExporter** [comment]
```
Sorry that isn't the issue after all.

I have no idea what the problem is other than some missing .properties file or 
some
locale error.
```

Original comment by `you.dont...@gmail.com` on 22 Jul 2009 at 5:22

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem...


$ java -jar JMugen.jar
Exception in thread "main" java.util.MissingResourceException: Can't find 
bundle for
base name render, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1521)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1260)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:715)
    at org.lee.mugen.renderer.GraphicsWrapper.init(GraphicsWrapper.java:10)
    at org.lee.mugen.test.TestMenu.main(TestMenu.java:11)
    at org.mugen.launch.Launch.main(Launch.java:13)
jasen@jasen-laptop:~/Desktop/JMugen.beta$
```

Original comment by `dreadyca...@gmail.com` on 28 Jul 2009 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
Java doesn't like files outside of .jar files.
Unpack contents of JMugen.jar file in the same directory and run jmugen with:
$ java org.mugen.launch.Launch

You will probably see a black screen.
That is because it can't find missing character files.
The problem is that Linux distinguishes low and upper case letters in paths as
different, while Windows doesn't.
Rename resource/chars/gokuHR/GokuHR.def to resource/chars/gokuHR/gokuHR.def
```

Original comment by `stiny...@gmail.com` on 16 Aug 2009 at 10:34

**Comment by GoogleCodeExporter** [comment]
```
I tried that but this is what I get in the terminal:

andy@andy-laptop:~/jmugen/JMugen$ java org.mugen.launch.Launch
Exception in thread "main" java.util.MissingResourceException: Can't find 
bundle for
base name render, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1278)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:733)
    at org.lee.mugen.renderer.GraphicsWrapper.init(GraphicsWrapper.java:10)
    at org.lee.mugen.test.TestMenu.main(TestMenu.java:11)
    at org.mugen.launch.Launch.main(Launch.java:13)
andy@andy-laptop:~/jmugen/JMugen$ 


```

Original comment by `andgomw...@gmail.com` on 16 Aug 2009 at 6:50

**Comment by GoogleCodeExporter** [comment]
```
It means you have render.properties files somewhere else.
Try to do the following:

$ cd
change current directory to your users's home

$ mkdir ~/jmugen
create a directory where you will be doing all unpacking

$ cp ~/downloads/JMugen.beta.rar ~/jmugen
copy downloaded JMugen.beta.rar in newly created folder

$ unrar x JMugen.beta.rar
unrar (note the option 'x' does not have preceding hyphen character)

$ unzip JMugen.jar
unzip

$ mv resource/chars/gokuHR/GokuHR.def resource/chars/gokuHR/gokuHR.def
make sure gokuHR is good

$ java org.mugen.launch.Launch
run JMugen

If you can't unrar/unzip it and get 'Command not found error' use:
$ sudo apt-get install unzip
$ sudo apt-get install unrar

works nicely for me...
```

Original comment by `rip...@gmail.com` on 16 Aug 2009 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
now I get this error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no gluegen-rt in
java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1698)
    at java.lang.Runtime.loadLibrary0(Runtime.java:840)
    at java.lang.System.loadLibrary(System.java:1047)
    at com.sun.gluegen.runtime.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:102)
    at com.sun.gluegen.runtime.NativeLibLoader.access$000(NativeLibLoader.java:51)
    at com.sun.gluegen.runtime.NativeLibLoader$1.run(NativeLibLoader.java:70)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.gluegen.runtime.NativeLibLoader.loadGlueGenRT(NativeLibLoader.java:68)
    at com.sun.gluegen.runtime.NativeLibrary.ensureNativeLibLoaded(NativeLibrary.java:399)
    at com.sun.gluegen.runtime.NativeLibrary.open(NativeLibrary.java:163)
    at com.sun.gluegen.runtime.NativeLibrary.open(NativeLibrary.java:129)
    at com.sun.opengl.impl.x11.DRIHack.begin(DRIHack.java:109)
    at com.sun.opengl.impl.x11.X11GLDrawableFactory.<clinit>(X11GLDrawableFactory.java:99)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:186)
    at javax.media.opengl.GLDrawableFactory.getFactory(GLDrawableFactory.java:111)
    at javax.media.opengl.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:520)
    at javax.media.opengl.GLCanvas.<init>(GLCanvas.java:131)
    at javax.media.opengl.GLCanvas.<init>(GLCanvas.java:90)
    at org.lee.mugen.renderer.jogl.JoglGameWindow.start(JoglGameWindow.java:278)
    at org.lee.mugen.test.TestMenu.main(TestMenu.java:14)
    at org.mugen.launch.Launch.main(Launch.java:13)

```

Original comment by `andgomw...@gmail.com` on 16 Aug 2009 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
I should also use 64 bit Ubuntu Jaunty Jackalope.  Would this also be a problem?
```

Original comment by `andgomw...@gmail.com` on 16 Aug 2009 at 8:48

**Comment by GoogleCodeExporter** [comment]
```
Concerning your question about usage of 64bit Ubuntu OS.
I'm using Debian 5 amd64bit, so it should run ok, since Ubuntu is somewhat 
Debian-based.

And the error message you get is indicating that you don't have native jogl 
libraries.
And there no such libraries in the distribution pack, because it is heavily
Windows-centric. Try:

$ sudo apt-get install libjogl-java
This will install required library in your system.
This package is available in universe package repository.
```

Original comment by `rip...@gmail.com` on 16 Aug 2009 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the help.  However I still get the same error.
```

Original comment by `andgomw...@gmail.com` on 17 Aug 2009 at 4:26

**Comment by GoogleCodeExporter** [comment]
```
does anyone else have this problem?


```

Original comment by `andgomw...@gmail.com` on 27 Aug 2009 at 6:47

**Comment by GoogleCodeExporter** [comment]
```
yep, right here, running Ubuntu intrepid (8.10) 32 bit and with the en-US 
locale. I 
get this when trying to run JMugen from terminal:

~/JMugen $ java -jar JMugen.jar
Exception in thread "main" java.util.MissingResourceException: Can't find 
bundle for 
base name render, locale en_US
    at 
java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1278)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:733)
    at org.lee.mugen.renderer.GraphicsWrapper.init(GraphicsWrapper.java:10)
    at org.lee.mugen.test.TestMenu.main(TestMenu.java:11)
    at org.mugen.launch.Launch.main(Launch.java:13)

```

Original comment by `m.cohomo...@gmail.com` on 14 Sep 2009 at 12:53

**Comment by GoogleCodeExporter** [comment]
```
Same problem here; 

Exception in thread "main" java.util.MissingResourceException: Can't find 
bundle for
base name render, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1521)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1260)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:715)
    at org.lee.mugen.renderer.GraphicsWrapper.init(GraphicsWrapper.java:10)
    at org.lee.mugen.test.TestMenu.main(TestMenu.java:11)
    at org.mugen.launch.Launch.main(Launch.java:13)
```

Original comment by `ryank...@gmail.com` on 11 Oct 2009 at 3:43
